 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPYgbiSHrfgqVA1Cojt7VVe6JL-mnHgrk',
    appId: '1:477379556977:web:787545017f1b3b52100dd0',
    messagingSenderId: '477379556977',
    projectId: 'mediapp-7da81',
    authDomain: 'mediapp-7da81.firebaseapp.com',
    storageBucket: 'mediapp-7da81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnEWvqrc4-FiAgQ3EQelMiTAZQn2PevM',
    appId: '1:477379556977:android:1eeee532b7e52e32100dd0',
    messagingSenderId: '477379556977',
    projectId: 'mediapp-7da81',
    storageBucket: 'mediapp-7da81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC3yqsbkC8jm1cSH6Q_mnM__kveHozYAE',
    appId: '1:477379556977:ios:36d79fef1f76224d100dd0',
    messagingSenderId: '477379556977',
    projectId: 'mediapp-7da81',
    storageBucket: 'mediapp-7da81.appspot.com',
    iosBundleId: 'com.example.mediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC3yqsbkC8jm1cSH6Q_mnM__kveHozYAE',
    appId: '1:477379556977:ios:2ed89c3c5ee668c6100dd0',
    messagingSenderId: '477379556977',
    projectId: 'mediapp-7da81',
    storageBucket: 'mediapp-7da81.appspot.com',
    iosBundleId: 'com.example.mediapp.RunnerTests',
  );
}
